

spring.application.name=user-service
server.port=8091

# Single H2 DB file for all services
spring.datasource.url=jdbc:h2:file:./data/UrbanVogueDB1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=dp
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT configuration
jwt.secret=urbanvogue-super-secret-key-for-tokengeneration-2026-very-secure-key expire token in 72 hours
jwt.expiration=259200000    