

spring.application.name=payment-service
server.port=8093

# Use the same DB file
spring.datasource.url=jdbc:h2:file:../data/UrbanVogueDB1;AUTO_SERVER=TRUE;
#spring.datasource.url=jdbc:h2:tcp://localhost/~/UrbanVogueDB1;DB_CLOSE_DELAY=-1
#spring.datasource.url=jdbc:h2:tcp://localhost:8082/C:/Users/dipanshu.patidar/UrbanVogueDB1;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=dp
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
